// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * Default Response
 */
export const zGetResponse = z.object({
    message: z.string()
});

/**
 * Default Response
 */
export const zGetSecurityAwnserResponse = z.object({
    securityQuestions: z.array(z.object({
        id: z.number(),
        question: z.string()
    }))
});

export const zPostCreateUserData = z.object({
    name: z.string(),
    password: z.string().min(8),
    displayName: z.string().optional(),
    securityAnswers: z.unknown()
});

/**
 * Default Response
 */
export const zPostCreateUserResponse = z.object({
    id: z.string(),
    name: z.string(),
    displayName: z.string().optional(),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime()
});

export const zPostLoginData = z.object({
    name: z.string().min(1),
    password: z.string()
});

/**
 * Default Response
 */
export const zPostLoginResponse = z.object({
    token: z.string()
});

/**
 * Default Response
 */
export const zGetProfileResponse = z.object({
    id: z.string(),
    name: z.string(),
    displayName: z.string().optional(),
    createdAt: z.string(),
    updatedAt: z.string()
});

export const zPostResetPasswordData = z.object({
    name: z.string(),
    securityAnswers: z.unknown(),
    newPassword: z.string().min(8)
});

/**
 * Default Response
 */
export const zPostResetPasswordResponse = z.object({
    message: z.string()
});